[profile.default]
src = 'src'
out = '_out'
test = 'test'
libs = ['lib']
fuzz_runs = 1024
gas_reports = ["*"]
# These compiler settings must match hardhat.config.ts to avoid unexpected issues
solc = "0.8.17"
optimizer = true
optimizer_runs = 200
ffi = true

[fmt]
multiline_func_header = "params_first"
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
