name: "CI"

env:
  FOUNDRY_PROFILE: "ci"
  ARBITRUM_GOERLI_RPC_URL: ""
  ARBITRUM_MAINNET_RPC_URL: ""
  DEV_PRIVATE_KEY: "0x0000000000000000000000000000000000000000000000000000000000000000"
  ARBITRUM_MAINNET_PK: "0x0000000000000000000000000000000000000000000000000000000000000000"
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "prod"
      - "develop"

jobs:

  lint-build-test:
    name: Lint+Build+Test
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [18.12.1]
    
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: "Build facet selector test script"
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Lint the contracts
        run: |
          yarn lint:check
          echo "## Contract lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Build the contracts
        run: |
          yarn build
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Run tests
        run: |
          yarn test
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY